name: name of Action

on: [push]

jobs:
  build:
    name: name of Build
    runs-on: ubuntu-latest
    steps:
      - name: name of step 1
        run: echo Hello World
        shell: bash
      - name: name of step 2
        run: echo `ls .. -a`
        shell: bash
      - name: name of step 3
        run: echo `ls -a`
        shell: bash
      - name: name of step 4
        run: echo `ls / -a`
        shell: bash
      - name: name of step 5
        run: echo `ls ~ -a`
        shell: bash
      - name: name of step 6
        run: echo `ls ~/work -a`
        shell: bash
      - name: name of step 7
        run: echo `ls ~/runners -a`
        shell: bash
      - name: name of step 8
        run: echo `ls ~/work/cicd -a`
        shell: bash
      - name: name of step 9
        run: echo `ls ~/work/cicd/cicd -a`
        shell: bash
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: name of step 10
        run: |
          python -m pip install --upgrade pip
          pip install pytest  
          pytest
        shell: bash