name: name of Action

on: [push]

jobs:
  build:
    name: name of Build
    runs-on: ubuntu-latest
    steps:
      - name: name of step 1
        run: echo Hello World
        shell: bash
      - name: name of step 2
        run: echo `ll`
        shell: bash